### ISSUE TITLE
Concatenate summary (-o) on push 'all' option and run tests in parallel

### ISSUE THREAD

**Issue by m-lukas** [homeport/gonut#84]
Currently, if pushing with the 'all' option, it runs a loop through all sample applications and pushes each app successively. Also it doesn't merge the summaries (if turned on) of the pushed applications but rather shows them in a row in between the staging logs.
To allow better automation and to spead up this process, it might make sense to run the pushes as goroutines and combine the summaries to one.

**Comment by HeavyWombat** [comment]
Closing as `gonut` will be archived soon.
